# Generated by Django 4.1 on 2022-12-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_user_from_chatmessages_emisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessages',
            old_name='emisor',
            new_name='user_from',
        ),
    ]
