# Generated by Django 4.1 on 2022-12-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0002_alter_avatar_imagen_comentariom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariom',
            name='subtitulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comentariom',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
