# Generated by Django 4.1 on 2022-12-15 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BLOG', '0002_comentariom_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariom',
            name='nombre',
            field=models.ForeignKey(default=1986, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
