# Generated by Django 4.1 on 2022-12-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0004_alter_comentariom_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentariom',
            name='imagen',
        ),
    ]
