# Generated by Django 4.1 on 2022-12-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0006_remove_comentariom_subtitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariom',
            name='imagen',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
