# Generated by Django 4.1 on 2022-12-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0007_comentariom_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariom',
            name='imagen',
            field=models.ImageField(upload_to='avatares'),
        ),
    ]
