# Generated by Django 4.1 on 2022-12-18 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0014_alter_comentariom_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariom',
            name='subtitulo',
            field=models.CharField(default='Sin Subtitulo', max_length=50),
        ),
        migrations.AddField(
            model_name='comentariom',
            name='titulo',
            field=models.CharField(default='Sin Titulo', max_length=50),
        ),
        migrations.AlterField(
            model_name='comentariom',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 16, 21, 24, 401400, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comentariom',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenBlog'),
        ),
    ]
