# Generated by Django 4.1 on 2022-12-20 12:49

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0015_comentariom_subtitulo_comentariom_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariom',
            name='campo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='comentariom',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 12, 49, 16, 696154, tzinfo=datetime.timezone.utc)),
        ),
    ]
