# Generated by Django 4.1 on 2022-12-20 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0016_alter_comentariom_campo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariom',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 22, 41, 8, 934488, tzinfo=datetime.timezone.utc)),
        ),
    ]
